#:schema node_modules/wrangler/config-schema.json
name = "git"
main = "src/index.js"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "git.kamal.sh", custom_domain = true },
  { pattern = "g.kamal.sh", custom_domain = true }
]

[triggers]
crons = ["0 0 * * *"] # Refresh repos daily at midnight
